"""Generate final data-kind output preview templates from registry ids.

The committed CSV/JSON files under ``storage/templates/data_kinds`` are materialized
output templates. Their field names are generated by resolving stable registry
ids to current registry payloads instead of typing column/key strings directly
into static files.
"""

from __future__ import annotations

import argparse
import csv
import filecmp
import json
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_TEMPLATE_ROOT = REPO_ROOT / "storage" / "templates" / "data_kinds"
DEFAULT_REGISTRY_CSV = Path("/root/projects/trading-main/registry/current.csv")


@dataclass(frozen=True)
class RegistryRef:
    """Stable registry id reference used inside generated template specs."""

    id: str
    expected_kinds: tuple[str, ...]


@dataclass(frozen=True)
class CsvTemplate:
    """CSV preview template specification."""

    relative_path: Path
    columns: Sequence[RegistryRef]
    row: Mapping[RegistryRef, Any]


@dataclass(frozen=True)
class JsonTemplate:
    """JSON preview template specification."""

    relative_path: Path
    payload: Mapping[RegistryRef | str, Any]


def field(item_id: str) -> RegistryRef:
    return RegistryRef(item_id, ("field", "temporal_field", "classification_field"))


def data_kind(item_id: str) -> RegistryRef:
    return RegistryRef(item_id, ("data_kind",))


# Field registry ids. Keep these values stable; do not replace them with
# literal output field names. The generator resolves ids to payload names.
DATA_KIND = field("fld_EKIND001")
SOURCE = field("fld_EKIND002")
INSTRUMENT_SYMBOL = field("fld_MKT001")
DATA_TIMEFRAME = field("fld_OPT014")
DATA_TIMESTAMP_ET = field("fld_OPT013")
INTERVAL_START_ET = field("fld_MKT002")
MACRO_METRIC = field("fld_MAC001")
OBSERVED_VALUE = field("fld_MAC004")

OPEN_PRICE = field("fld_OPT015")
HIGH_PRICE = field("fld_OPT016")
LOW_PRICE = field("fld_OPT017")
CLOSE_PRICE = field("fld_OPT018")
VOLUME = field("fld_OPT019")
TRADE_COUNT = field("fld_OPT020")
VWAP = field("fld_OPT021")

QUOTE_COUNT = field("fld_MKT004")
QUOTE_AVG_BID = field("fld_MKT011")
QUOTE_AVG_ASK = field("fld_MKT012")
QUOTE_AVG_MID = field("fld_MKT013")
QUOTE_AVG_SPREAD = field("fld_MKT014")
QUOTE_LAST_BID = field("fld_MKT015")
QUOTE_LAST_ASK = field("fld_MKT016")
QUOTE_LAST_MID = field("fld_MKT017")
VWAP_MINUS_QUOTE_AVG_MID = field("fld_MKT018")

TIMELINE_ID = field("fld_A7K3P2Q9")
TIMELINE_HEADLINE = field("fld_EVT001")
TIMELINE_CREATED_AT = field("fld_P8L2C4TY")
TIMELINE_UPDATED_AT = field("fld_Q5F9M2NZ")
TIMELINE_SYMBOLS = field("fld_EVT005")
TIMELINE_SUMMARY = field("fld_EVT020")
TIMELINE_URL = field("fld_EVT007")
EVENT_ID = field("fld_EVT010")
EVENT_SECURITY_ID = field("fld_EVT011")
EVENT_SYMBOL = field("fld_MKT001")
EVENT_TIME_ET = field("fld_EVT013")
EVENT_EFFECTIVE_TIME_ET = field("fld_EVT014")
EVENT_TYPE = field("fld_EVT015")
EVENT_SOURCE_TYPE = field("fld_EVT016")
EVENT_SOURCE_REF = field("fld_EVT017")
EVENT_SOURCE_URL = field("fld_EVT018")
EVENT_TITLE = field("fld_EVT019")
EVENT_SUMMARY = field("fld_EVT020")
EVENT_ANALYSIS_REPORT_URL = field("fld_EVT021")
EVENT_ANALYSIS_STATUS = field("fld_EVT022")
EVENT_DIRECTION_SCORE = field("fld_EVT023")
EVENT_MAGNITUDE_SCORE = field("fld_EVT024")
EVENT_SURPRISE_SCORE = field("fld_EVT025")
EVENT_NOVELTY_SCORE = field("fld_EVT026")
EVENT_RELEVANCE_SCORE = field("fld_EVT027")
EVENT_CREDIBILITY_SCORE = field("fld_EVT028")
EVENT_PRICE_IN_SCORE = field("fld_EVT029")
EVENT_REACTION_SCORE = field("fld_EVT030")
EVENT_FACTOR_AS_OF_ET = field("fld_EVT031")
EVENT_FACTOR_VERSION = field("fld_EVT032")
EVENT_REPORT_ID = field("fld_EVT033")
EVENT_REPORT_URL = field("fld_EVT034")
EVENT_REPORT_JSON_URL = field("fld_EVT035")
EVENT_ANALYSIS_MODEL = field("fld_EVT036")
GENERATED_AT_ET = field("fld_EVT037")
EVENT_TAXONOMY_CONTEXT = field("fld_EVT038")
EVENT_CANONICAL_EVENT_ID = field("fld_EVT039")
EVENT_DEDUP_STATUS = field("fld_EVT040")
EVENT_SOURCE_PRIORITY = field("fld_EVT041")
EVENT_COVERAGE_REASON = field("fld_EVT042")
EVENT_IMPACT_SCOPE = field("fld_EVT043")
EVENT_IMPACTED_UNIVERSE = field("fld_EVT044")
EVENT_PRIMARY_IMPACT_TARGET = field("fld_EVT045")
GDELT_ARTICLE_ID = field("fld_GDLT001")
GDELT_ARTICLE_SEEN_AT_UTC = field("fld_GDLT002")
GDELT_SOURCE_DOMAIN = field("fld_GDLT003")
GDELT_ARTICLE_URL = field("fld_EVT007")
GDELT_ARTICLE_LANGUAGE = field("fld_GDLT005")
GDELT_SOURCE_COUNTRY = field("fld_GDLT006")
GDELT_ARTICLE_TITLE = field("fld_EVT019")
SOURCE_THEME_TAGS = field("fld_GDLT008")
GDELT_PERSONS = field("fld_GDLT009")
GDELT_ORGANIZATIONS = field("fld_GDLT010")
GDELT_LOCATIONS = field("fld_GDLT011")
GDELT_TONE = field("fld_GDLT012")
GDELT_SHARING_IMAGE = field("fld_GDLT013")
GDELT_SOURCE_TYPE = field("fld_EVT016")

TRADING_ECONOMICS_EVENT_TIME_ET = field("fld_EVT013")
TRADING_ECONOMICS_COUNTRY = field("fld_TEC002")
TRADING_ECONOMICS_EVENT = field("fld_TEC003")
SOURCE_EVENT_TYPE = field("fld_TEC004")
TRADING_ECONOMICS_REFERENCE = field("fld_TEC005")
TRADING_ECONOMICS_ACTUAL = field("fld_TEC006")
TRADING_ECONOMICS_PREVIOUS = field("fld_TEC007")
TRADING_ECONOMICS_CONSENSUS = field("fld_TEC008")
TRADING_ECONOMICS_FORECAST = field("fld_TEC009")
TRADING_ECONOMICS_REVISED = field("fld_TEC010")
TRADING_ECONOMICS_IMPORTANCE = field("fld_TEC011")
TRADING_ECONOMICS_SYMBOL = field("fld_MKT001")
TRADING_ECONOMICS_SOURCE_URL = field("fld_EVT018")

ETF_TICKER = field("fld_ETFH001")
ETF_ISSUER = field("fld_ETFH002")
ETF_HOLDINGS_AS_OF_DATE = field("fld_ETFH003")
ETF_HOLDING_TICKER = field("fld_ETFH004")
ETF_HOLDING_NAME = field("fld_ETFH005")
ETF_HOLDING_WEIGHT = field("fld_ETFH006")
ETF_HOLDING_SHARES = field("fld_ETFH007")
ETF_HOLDING_MARKET_VALUE = field("fld_ETFH008")
ETF_HOLDING_CUSIP = field("fld_ETFH009")
ETF_HOLDING_SEDOL = field("fld_ETFH010")
ETF_HOLDING_ASSET_CLASS = field("fld_ETFH011")
SECTOR_TYPE = field("fld_ETFH012")
ETF_HOLDING_SOURCE_URL = field("fld_EVT018")

STOCK_ETF_EXPOSURE_AS_OF_DATE = field("fld_ETFH003")
STOCK_ETF_EXPOSURE_SYMBOL = field("fld_MKT001")
STOCK_ETF_EXPOSED_ETFS = field("fld_STKEX003")
STOCK_ETF_TOP_EXPOSURE_ETF = field("fld_STKEX004")
STOCK_ETF_TOTAL_EXPOSURE_SCORE = field("fld_STKEX005")
STOCK_ETF_WEIGHTED_SECTOR_SCORE = field("fld_STKEX006")
STOCK_ETF_WEIGHTED_THEME_SCORE = field("fld_STKEX007")
EXPOSURE_TAGS = field("fld_STKEX008")
STOCK_ETF_SOURCE_ETF_COUNT = field("fld_STKEX009")
STOCK_ETF_SOURCE_SNAPSHOT_REFS = field("fld_STKEX010")
STOCK_ETF_AVAILABLE_TIME_ET = field("fld_STKEX011")

ABNORMAL_ACTIVITY_TYPE = field("fld_ABN001")
ABNORMAL_ACTIVITY_EVIDENCE_WINDOW = field("fld_ABN002")
RETURN_ZSCORE = field("fld_ABN003")
VOLUME_ZSCORE = field("fld_ABN004")
RELATIVE_STRENGTH_ZSCORE = field("fld_ABN005")
GAP_PCT = field("fld_ABN006")
LIQUIDITY_SPREAD_ZSCORE = field("fld_ABN007")
EQUITY_ABNORMAL_ACTIVITY_SOURCE_REFS = field("fld_ABN008")

OPTION_UNDERLYING = field("fld_OPT001")
OPTION_EXPIRATION = field("fld_OPT002")
OPTION_RIGHT = field("fld_OPT003")
OPTION_STRIKE = field("fld_OPT004")
SNAPSHOT_TIME_ET = field("fld_OPT005")
OPTION_CONTRACT_COUNT = field("fld_OPT006")
OPTION_CONTRACTS = field("fld_OPT007")
OPTION_QUOTE_CONTEXT = field("fld_OPT008")
IV_CONTEXT = field("fld_OPT009")
GREEKS_CONTEXT = field("fld_OPT010")
OPTION_UNDERLYING_CONTEXT = field("fld_OPT011")
DERIVED_CONTEXT = field("fld_OPT012")
QUOTE_BID = field("fld_OPT032")
QUOTE_ASK = field("fld_OPT033")
QUOTE_MID = field("fld_OPT034")
QUOTE_SPREAD = field("fld_OPT035")
QUOTE_SPREAD_PCT = field("fld_OPT036")
QUOTE_BID_SIZE = field("fld_OPT037")
QUOTE_ASK_SIZE = field("fld_OPT038")
IMPLIED_VOL = field("fld_OPT045")
GREEK_DELTA = field("fld_OPT051")
GREEK_THETA = field("fld_OPT052")
GREEK_VEGA = field("fld_OPT053")
GREEK_RHO = field("fld_OPT054")
GREEK_EPSILON = field("fld_OPT055")
GREEK_LAMBDA = field("fld_OPT056")
UNDERLYING_PRICE = field("fld_OPT057")
UNDERLYING_TIMESTAMP_ET = field("fld_OPT058")
OPTION_DAYS_TO_EXPIRATION = field("fld_OPT059")
QUOTE_BID_EXCHANGE = field("fld_OPT060")
QUOTE_ASK_EXCHANGE = field("fld_OPT061")
QUOTE_BID_CONDITION = field("fld_OPT062")
QUOTE_ASK_CONDITION = field("fld_OPT063")
IV_ERROR = field("fld_OPT064")

OPTION_EVENT_DETAIL_EVENT_ID = field("fld_EVT010")
OPTION_EVENT_DETAIL_CONTRACT = field("fld_OPD002")
OPTION_CONTRACT_SYMBOL = field("fld_OPD003")
OPTION_EVENT_DETAIL_TRIGGERED_INDICATORS = field("fld_OPD004")
OPTION_EVENT_DETAIL_EVIDENCE_WINDOW = field("fld_ABN002")
WINDOW_START_ET = field("fld_OPD006")
WINDOW_END_ET = field("fld_OPD007")
OPTION_EVENT_DETAIL_TRIGGERING_TRADE = field("fld_OPD008")
TRADE_SIDE_TYPE = field("fld_OPD009")
OPTION_EVENT_DETAIL_QUOTE_CONTEXT = field("fld_OPD010")
OPTION_EVENT_DETAIL_IV_CONTEXT = field("fld_OPD011")
IV_PERCENTILE_BY_EXPIRATION = field("fld_OPD012")
OPTION_EVENT_DETAIL_SOURCE_REFS = field("fld_ABN008")
OPTION_EVENT_DETAIL_PROVIDER = field("fld_OPD014")
OPTION_EVENT_DETAIL_RAW_PERSISTENCE = field("fld_OPD015")
TRADE_TIMESTAMP_ET = field("fld_OPD016")
TRADE_SIZE = field("fld_OPD018")
OPTION_EVENT_TRIGGER_TRADE_AT_ASK = field("fld_OPD019")
OPTION_EVENT_TRIGGER_OPENING_ACTIVITY = field("fld_OPD020")
OPTION_EVENT_TRIGGER_IV_HIGH_CROSS_SECTION = field("fld_OPD021")
OPTION_EVENT_DETAIL_STATISTICS = field("fld_OPD022")
TRADE_PRICE = field("fld_OPD024")
OPTION_EVENT_DETAIL_PRICE_VS_ASK = field("fld_OPD028")
WINDOW_TRADE_COUNT = field("fld_OPD030")
WINDOW_VOLUME = field("fld_OPD031")
WINDOW_NOTIONAL = field("fld_OPD032")
FIRST_SEEN_IN_WINDOW = field("fld_OPD033")
OPTION_EVENT_DETAIL_ASK_TOUCH_RATIO = field("fld_OPD037")
CONTRACT_PRIOR_WINDOW_VOLUME = field("fld_OPD038")
VOLUME_VS_PRIOR_WINDOW_RATIO = field("fld_OPD039")
VOLUME_PERCENTILE_20D_SAME_TIME = field("fld_OPD040")
EXPIRATION_CHAIN_CONTRACT_COUNT = field("fld_OPD041")
IV_RANK_IN_EXPIRATION = field("fld_OPD042")
IV_ZSCORE_BY_EXPIRATION = field("fld_OPD043")
OPTION_EVENT_DETAIL_STANDARD_CONTEXT = field("fld_OPD044")
OPTION_EVENT_DETAIL_STANDARD_SOURCE = field("fld_OPD045")
OPTION_EVENT_DETAIL_STANDARD_ID = field("fld_OPD046")

OPTION_EVENT_DETAIL_CURRENT_STANDARD = field("fld_OPD048")
OPTION_EVENT_STANDARD_MAX_PRICE_VS_ASK = field("fld_OPD049")
OPTION_EVENT_STANDARD_MIN_ASK_TOUCH_RATIO = field("fld_OPD050")
OPTION_EVENT_STANDARD_MIN_WINDOW_VOLUME = field("fld_OPD051")
OPTION_EVENT_STANDARD_MIN_VOLUME_PERCENTILE_20D_SAME_TIME = field("fld_OPD052")
OPTION_EVENT_STANDARD_MIN_IV_PERCENTILE_BY_EXPIRATION = field("fld_OPD053")
OPTION_EVENT_STANDARD_MIN_IV_ZSCORE_BY_EXPIRATION = field("fld_OPD054")

# Data-kind registry ids.
EQUITY_BAR = data_kind("dki_TOYRS7UZ")
EQUITY_LIQUIDITY_BAR = data_kind("dki_64LQWJCW")
EQUITY_NEWS = data_kind("dki_1KW5CB9R")
CRYPTO_BAR = data_kind("dki_O9BGKU9V")
CRYPTO_LIQUIDITY_BAR = data_kind("dki_OKXLIQBR")
OPTION_ACTIVITY_EVENT = data_kind("dki_OPEVENT1")
OPTION_ACTIVITY_EVENT_DETAIL = data_kind("dki_OPDET01")
OPTION_BAR = data_kind("dki_OPBAR001")
OPTION_CHAIN_SNAPSHOT = data_kind("dki_OPCHAIN1")
MACRO_RELEASE_EVENT = data_kind("dki_MACREVT1")
GDELT_ARTICLE = data_kind("dki_GDELTART")
TRADING_ECONOMICS_CALENDAR_EVENT = data_kind("dki_TECALWEB")
ETF_HOLDINGS_SNAPSHOT = data_kind("dki_NFRKHNJO")
STOCK_ETF_EXPOSURE = data_kind("dki_STKETFEX")
EQUITY_ABNORMAL_ACTIVITY_EVENT = data_kind("dki_EQABNACT")
TRADING_EVENT = data_kind("dki_TREVT001")
EVENT_FACTOR = data_kind("dki_TREVT002")
EVENT_ANALYSIS_REPORT = data_kind("dki_TREVT003")


class Registry:
    """Read current registry payloads by stable id."""

    def __init__(self, registry_csv: Path):
        with registry_csv.open(newline="", encoding="utf-8") as handle:
            rows = list(csv.DictReader(handle))
        self._by_id = {row["id"]: row for row in rows}

    def payload(self, ref: RegistryRef) -> str:
        row = self._by_id.get(ref.id)
        if row is None:
            raise KeyError(f"Registry id not found: {ref.id}")
        if row["kind"] not in ref.expected_kinds:
            raise ValueError(
                f"Registry id {ref.id} expected kind in {ref.expected_kinds}, got kind={row['kind']}"
            )
        return row["payload"]


def resolve(value: Any, registry: Registry) -> Any:
    """Resolve registry refs recursively in generated template specs."""
    if isinstance(value, RegistryRef):
        return registry.payload(value)
    if isinstance(value, Mapping):
        return {resolve(key, registry): resolve(child, registry) for key, child in value.items()}
    if isinstance(value, list):
        return [resolve(child, registry) for child in value]
    if isinstance(value, tuple):
        return [resolve(child, registry) for child in value]
    return value


def csv_template(relative_path: str, columns: Sequence[RegistryRef], values: Sequence[Any]) -> CsvTemplate:
    if len(columns) != len(values):
        raise ValueError(f"CSV template {relative_path} has mismatched columns and values")
    return CsvTemplate(Path(relative_path), columns, dict(zip(columns, values)))


CSV_TEMPLATES: tuple[CsvTemplate, ...] = (
    csv_template(
        "gdelt/gdelt_article.preview.csv",
        [GDELT_ARTICLE_ID, GDELT_ARTICLE_SEEN_AT_UTC, GDELT_SOURCE_DOMAIN, GDELT_ARTICLE_URL, GDELT_ARTICLE_LANGUAGE, GDELT_SOURCE_COUNTRY, GDELT_ARTICLE_TITLE, SOURCE_THEME_TAGS, GDELT_PERSONS, GDELT_ORGANIZATIONS, GDELT_LOCATIONS, GDELT_TONE, GDELT_SHARING_IMAGE, EVENT_IMPACT_SCOPE, GDELT_SOURCE_TYPE],
        ["20260427123000-1", "2026-04-27T12:30:00Z", "example.com", "https://example.com/politics-economy-tech", "", "", "", "ECON_STOCKMARKET;TAX_FNCACT", "", "Federal Reserve", "US#United States#US", -1.2, "https://example.com/image.jpg", "market;sector;industry;theme", "gdelt_gkg_article"],
    ),
    csv_template(
        "trading_economics/trading_economics_calendar_event.preview.csv",
        [TRADING_ECONOMICS_EVENT_TIME_ET, TRADING_ECONOMICS_COUNTRY, TRADING_ECONOMICS_EVENT, SOURCE_EVENT_TYPE, TRADING_ECONOMICS_REFERENCE, TRADING_ECONOMICS_ACTUAL, TRADING_ECONOMICS_PREVIOUS, TRADING_ECONOMICS_CONSENSUS, TRADING_ECONOMICS_FORECAST, TRADING_ECONOMICS_REVISED, TRADING_ECONOMICS_IMPORTANCE, TRADING_ECONOMICS_SYMBOL, TRADING_ECONOMICS_SOURCE_URL],
        ["2026-04-03T08:30:00-04:00", "United States", "Non Farm Payrolls", "Labour", "Mar", "228K", "117K", "135K", "140K", "", "3", "", "https://tradingeconomics.com/united-states/calendar"],
    ),
    csv_template(
        "etf/etf_holding_snapshot.preview.csv",
        [ETF_TICKER, ETF_ISSUER, ETF_HOLDINGS_AS_OF_DATE, ETF_HOLDING_TICKER, ETF_HOLDING_NAME, ETF_HOLDING_WEIGHT, ETF_HOLDING_SHARES, ETF_HOLDING_MARKET_VALUE, ETF_HOLDING_CUSIP, ETF_HOLDING_SEDOL, ETF_HOLDING_ASSET_CLASS, SECTOR_TYPE, ETF_HOLDING_SOURCE_URL],
        ["VGT", "vanguard", "2026-04-24", "NVDA", "NVIDIA Corp.", 18.53, 129246346, 22540562742, "67066G104", "2379504", "Equity", "Information Technology", "https://investor.vanguard.com/investment-products/etfs/profile/vgt"],
    ),
    csv_template(
        "model_inputs/stock_etf_exposure.preview.csv",
        [STOCK_ETF_EXPOSURE_AS_OF_DATE, STOCK_ETF_EXPOSURE_SYMBOL, STOCK_ETF_EXPOSED_ETFS, STOCK_ETF_TOP_EXPOSURE_ETF, STOCK_ETF_TOTAL_EXPOSURE_SCORE, STOCK_ETF_WEIGHTED_SECTOR_SCORE, STOCK_ETF_WEIGHTED_THEME_SCORE, EXPOSURE_TAGS, STOCK_ETF_SOURCE_ETF_COUNT, STOCK_ETF_SOURCE_SNAPSHOT_REFS, STOCK_ETF_AVAILABLE_TIME_ET],
        ["2026-04-24", "NVDA", "QQQ;XLK;SMH;SOXX;AIQ", "SMH", 0.92, 0.93, 0.88, "semiconductor;AI;large_cap_growth;high_beta", 5, "VGT:2026-04-24;SMH:2026-04-24;QQQ:2026-04-24", "2026-04-25T09:30:00-04:00"],
    ),
    csv_template(
        "events/macro_release_event.preview.csv",
        [EVENT_ID, EVENT_CANONICAL_EVENT_ID, EVENT_DEDUP_STATUS, EVENT_SOURCE_PRIORITY, EVENT_IMPACT_SCOPE, EVENT_IMPACTED_UNIVERSE, EVENT_PRIMARY_IMPACT_TARGET, EVENT_SECURITY_ID, EVENT_SYMBOL, EVENT_TIME_ET, EVENT_EFFECTIVE_TIME_ET, EVENT_TYPE, EVENT_SOURCE_TYPE, EVENT_SOURCE_REF, EVENT_SOURCE_URL, EVENT_TITLE, EVENT_SUMMARY, MACRO_METRIC, OBSERVED_VALUE, EVENT_ANALYSIS_REPORT_URL, EVENT_ANALYSIS_STATUS, EVENT_COVERAGE_REASON, EVENT_TAXONOMY_CONTEXT],
        ["macro_evt_P8Q4W6R2", "macro_evt_P8Q4W6R2", "canonical", 100, "market", "US_MARKET;rates;USD;equities", "US_MARKET", "", "", "2026-04-10T08:30:00-04:00", "2026-04-10T08:30:00-04:00", "macro_release_event", "official_macro_release", "cpi_yoy", "https://www.bls.gov/news.release/cpi.htm", "CPI YoY macro release", "Official CPI release became observable at 08:30 ET and may affect broad market, rates, USD, and equity risk appetite.", "cpi_yoy", 3.2, "", "not_requested", "official macro release is source of truth", '{"provider":"bls","consensus_source":"not_available","surprise_status":"pending_consensus_source"}'],
    ),
    csv_template(
        "alpaca/equity_bar.preview.csv",
        [INSTRUMENT_SYMBOL, DATA_TIMEFRAME, DATA_TIMESTAMP_ET, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, VOLUME, VWAP, TRADE_COUNT],
        ["AAPL", "1Day", "2024-01-02T00:00:00-05:00", 187.15, 188.44, 183.885, 185.64, 82496943, 185.846233, 1009074],
    ),
    csv_template(
        "alpaca/equity_liquidity_bar.preview.csv",
        [INSTRUMENT_SYMBOL, DATA_TIMEFRAME, INTERVAL_START_ET, TRADE_COUNT, QUOTE_COUNT, VOLUME, VWAP, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, QUOTE_AVG_BID, QUOTE_AVG_ASK, QUOTE_AVG_MID, QUOTE_AVG_SPREAD, QUOTE_LAST_BID, QUOTE_LAST_ASK, QUOTE_LAST_MID, VWAP_MINUS_QUOTE_AVG_MID],
        ["AAPL", "1Min", "2024-01-02T09:30:00-05:00", 1000, 1000, 53862, 187.0966001819, 187.18, 187.25, 186.35, 187.06, 187.06611, 187.09592, 187.081015, 0.02981, 187.0, 187.05, 187.025, 0.0155851819],
    ),
    csv_template(
        "alpaca/equity_news.preview.csv",
        [TIMELINE_ID, TIMELINE_HEADLINE, TIMELINE_CREATED_AT, TIMELINE_UPDATED_AT, TIMELINE_SYMBOLS, TIMELINE_SUMMARY, TIMELINE_URL],
        [36564250, "Bank Of America Predicts 10 2024 Market Surprises: From Booming IPOs To Japanese Equity Surge", "2024-01-09T14:46:19-05:00", "2024-01-09T14:46:19-05:00", "AAPL;EWJ;IHE;KBE;NVDA", "Bank of America lists 10 market surprises...", "https://www.benzinga.com/..."],
    ),
    csv_template(
        "events/trading_event.preview.csv",
        [EVENT_ID, EVENT_CANONICAL_EVENT_ID, EVENT_DEDUP_STATUS, EVENT_SOURCE_PRIORITY, EVENT_IMPACT_SCOPE, EVENT_IMPACTED_UNIVERSE, EVENT_PRIMARY_IMPACT_TARGET, EVENT_SECURITY_ID, EVENT_SYMBOL, EVENT_TIME_ET, EVENT_EFFECTIVE_TIME_ET, EVENT_TYPE, EVENT_SOURCE_TYPE, EVENT_SOURCE_REF, EVENT_SOURCE_URL, EVENT_TITLE, EVENT_SUMMARY, EVENT_ANALYSIS_REPORT_URL, EVENT_ANALYSIS_STATUS, EVENT_COVERAGE_REASON, EVENT_TAXONOMY_CONTEXT],
        ["evt_Q7M4N2PX", "evt_Q7M4N2PX", "canonical", 100, "security", "AAPL", "AAPL", "AAPL", "AAPL", "2026-01-30T16:05:00-05:00", "2026-02-02T09:30:00-05:00", "equity_financial_report_event", "sec_filing", "0000320193-26-000012", "https://www.sec.gov/Archives/edgar/data/320193/000032019326000012/", "AAPL files 10-K annual report", "Apple filed a 10-K annual report after market close.", "reports/evt_Q7M4N2PX.md", "succeeded", "official SEC filing is source of truth", '{"sec_form":"10-K","sec_items":[]}'],
    ),
    csv_template(
        "events/equity_abnormal_activity_event.preview.csv",
        [EVENT_ID, EVENT_SYMBOL, EVENT_TIME_ET, EVENT_EFFECTIVE_TIME_ET, EVENT_TYPE, EVENT_SOURCE_TYPE, EVENT_TITLE, EVENT_SUMMARY, ABNORMAL_ACTIVITY_TYPE, ABNORMAL_ACTIVITY_EVIDENCE_WINDOW, RETURN_ZSCORE, VOLUME_ZSCORE, RELATIVE_STRENGTH_ZSCORE, GAP_PCT, LIQUIDITY_SPREAD_ZSCORE, EQUITY_ABNORMAL_ACTIVITY_SOURCE_REFS, EVENT_TAXONOMY_CONTEXT],
        ["eq_abn_N7K4Q2MX", "NVDA", "2026-04-24T09:35:00-04:00", "2026-04-24T09:36:00-04:00", "equity_abnormal_activity_event", "alpaca_equity_market_data", "NVDA abnormal opening move with volume expansion", "NVDA showed abnormal return and volume versus recent same-time windows and sector benchmark.", "return_zscore;volume_spike;sector_relative_move", '{"timeframe":"5Min","window_start_et":"2026-04-24T09:30:00-04:00","window_end_et":"2026-04-24T09:35:00-04:00","lookback_days":20}', 3.1, 4.8, 2.2, 1.4, 0.7, "alpaca_bars:NVDA:2026-04-24T09:30;alpaca_liquidity:NVDA:2026-04-24T09:30;sector:SMH", '{"benchmark":"SMH","detector":"equity_abnormal_activity_v0"}'],
    ),
    csv_template(
        "events/event_factor.preview.csv",
        [EVENT_ID, EVENT_CANONICAL_EVENT_ID, EVENT_IMPACT_SCOPE, EVENT_IMPACTED_UNIVERSE, EVENT_PRIMARY_IMPACT_TARGET, EVENT_SECURITY_ID, EVENT_SYMBOL, EVENT_TYPE, EVENT_EFFECTIVE_TIME_ET, EVENT_FACTOR_AS_OF_ET, EVENT_DIRECTION_SCORE, EVENT_MAGNITUDE_SCORE, EVENT_SURPRISE_SCORE, EVENT_NOVELTY_SCORE, EVENT_RELEVANCE_SCORE, EVENT_CREDIBILITY_SCORE, EVENT_PRICE_IN_SCORE, EVENT_REACTION_SCORE, EVENT_FACTOR_VERSION, EVENT_ANALYSIS_REPORT_URL],
        ["evt_Q7M4N2PX", "evt_Q7M4N2PX", "security", "AAPL", "AAPL", "AAPL", "AAPL", "equity_financial_report_event", "2026-02-02T09:30:00-05:00", "2026-02-02T09:31:00-05:00", 0.2, 0.7, -0.1, 0.8, 1.0, 1.0, 0.3, "", "event_factor_v0", "reports/evt_Q7M4N2PX.md"],
    ),
    csv_template(
        "events/event_analysis_report.preview.csv",
        [EVENT_REPORT_ID, EVENT_ID, EVENT_CANONICAL_EVENT_ID, EVENT_DEDUP_STATUS, EVENT_IMPACT_SCOPE, EVENT_IMPACTED_UNIVERSE, EVENT_PRIMARY_IMPACT_TARGET, EVENT_SECURITY_ID, EVENT_SYMBOL, EVENT_TYPE, EVENT_SOURCE_TYPE, EVENT_SOURCE_REF, EVENT_SOURCE_URL, EVENT_REPORT_URL, EVENT_REPORT_JSON_URL, EVENT_ANALYSIS_STATUS, EVENT_ANALYSIS_MODEL, GENERATED_AT_ET, EVENT_TITLE, EVENT_SUMMARY, EVENT_COVERAGE_REASON, EVENT_TAXONOMY_CONTEXT],
        ["rpt_H4D8K2QA", "evt_Q7M4N2PX", "evt_Q7M4N2PX", "canonical", "security", "AAPL", "AAPL", "AAPL", "AAPL", "equity_financial_report_event", "sec_filing", "0000320193-26-000012", "https://www.sec.gov/Archives/edgar/data/320193/000032019326000012/", "reports/evt_Q7M4N2PX.md", "reports/evt_Q7M4N2PX.analysis.json", "succeeded", "financial_report_agent_v0", "2026-02-02T09:31:00-05:00", "AAPL 10-K analysis", "Agent-generated report artifact index for an SEC financial report event.", "official SEC filing is source of truth", '{"sec_form":"10-K","report_kind":"markdown_plus_json_sidecar"}'],
    ),
    csv_template(
        "okx/crypto_bar.preview.csv",
        [INSTRUMENT_SYMBOL, DATA_TIMEFRAME, DATA_TIMESTAMP_ET, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, VOLUME, VWAP, TRADE_COUNT],
        ["BTC-USDT", "1Min", "2026-04-26T18:13:00-04:00", 78527.3, 78535.1, 78527.2, 78535.1, 0.0013739, "", ""],
    ),
    csv_template(
        "okx/crypto_liquidity_bar.preview.csv",
        [INSTRUMENT_SYMBOL, DATA_TIMEFRAME, INTERVAL_START_ET, TRADE_COUNT, QUOTE_COUNT, VOLUME, VWAP, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, QUOTE_AVG_BID, QUOTE_AVG_ASK, QUOTE_AVG_MID, QUOTE_AVG_SPREAD, QUOTE_LAST_BID, QUOTE_LAST_ASK, QUOTE_LAST_MID, VWAP_MINUS_QUOTE_AVG_MID],
        ["BTC-USDT", "1Min", "2026-04-26T18:13:00-04:00", 1, "", 0.0013739, 78535.1, 78535.1, 78535.1, 78535.1, 78535.1, "", "", "", "", "", "", "", ""],
    ),
    csv_template(
        "thetadata/option_activity_event.preview.csv",
        [TIMELINE_ID, TIMELINE_HEADLINE, TIMELINE_CREATED_AT, TIMELINE_UPDATED_AT, TIMELINE_SYMBOLS, TIMELINE_SUMMARY, TIMELINE_URL],
        ["opt_evt_N7Q4K2M9", "AAPL May 15 270C draws opening ask-side activity with elevated IV", "2026-04-24T09:30:02.267000-04:00", "2026-04-24T09:30:02.500000-04:00", "AAPL;AAPL 2026-05-15 270C", "trade_at_ask;opening_activity;iv_high_cross_section", "opt_evt_N7Q4K2M9.csv"],
    ),
    csv_template(
        "thetadata/option_activity_event_detail.preview.csv",
        [OPTION_EVENT_DETAIL_EVENT_ID, TIMELINE_CREATED_AT, TIMELINE_UPDATED_AT, OPTION_UNDERLYING, OPTION_EXPIRATION, OPTION_RIGHT, OPTION_STRIKE, OPTION_CONTRACT_SYMBOL, OPTION_EVENT_DETAIL_TRIGGERED_INDICATORS, OPTION_EVENT_DETAIL_EVIDENCE_WINDOW, OPTION_EVENT_DETAIL_TRIGGERING_TRADE, OPTION_EVENT_DETAIL_QUOTE_CONTEXT, OPTION_EVENT_DETAIL_IV_CONTEXT, OPTION_EVENT_DETAIL_SOURCE_REFS],
        ["opt_evt_N7Q4K2M9", "2026-04-24T09:30:02.267000-04:00", "2026-04-24T09:30:02.500000-04:00", "AAPL", "2026-05-15", "CALL", 270.0, "AAPL 2026-05-15 270C", '{"trade_at_ask":{"statistics":{"trade_price":1.25,"ask_touch_ratio":1.0},"current_standard":{"max_price_vs_ask":0.01,"min_ask_touch_ratio":0.95}}}', '{"timeframe":"30Min","window_start_et":"2026-04-24T09:30:00-04:00","window_end_et":"2026-04-24T10:00:00-04:00"}', '{"trade_side_type":"ask_side","trade_timestamp_et":"2026-04-24T09:30:02.267000-04:00","trade_price":1.25,"trade_size":80}', '{"timestamp_et":"2026-04-24T09:30:02.260000-04:00","bid":1.15,"ask":1.25,"mid":1.2}', '{"implied_vol":0.64,"iv_percentile_by_expiration":0.97}', '{"provider":"thetadata","raw_persistence":"not_persisted_by_default"}'],
    ),
    csv_template(
        "thetadata/option_bar.preview.csv",
        [OPTION_UNDERLYING, OPTION_EXPIRATION, OPTION_RIGHT, OPTION_STRIKE, DATA_TIMEFRAME, DATA_TIMESTAMP_ET, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, VOLUME, TRADE_COUNT, VWAP],
        ["AAPL", "2026-05-15", "CALL", 270.0, "1Min", "2026-04-24T09:30:00-04:00", 9.4, 9.4, 8.26, 8.26, 21, 8, 8.71],
    ),
    csv_template(
        "thetadata/option_chain_snapshot.preview.csv",
        [OPTION_UNDERLYING, SNAPSHOT_TIME_ET, OPTION_CONTRACT_COUNT, OPTION_CONTRACTS],
        ["AAPL", "2026-04-24T16:00:00-04:00", 3120, '[{"expiration":"2026-04-27","right":"CALL","strike":270.0,"quote":{"bid":3.35,"ask":3.55,"mid":3.45},"iv":{"implied_vol":0.3124},"greeks":{"delta":0.52}}]'],
    ),
)

JSON_TEMPLATES: tuple[JsonTemplate, ...] = ()


def all_template_paths() -> list[Path]:
    """Return all generated preview template paths relative to the template root."""
    return [template.relative_path for template in CSV_TEMPLATES] + [
        template.relative_path for template in JSON_TEMPLATES
    ]


def write_csv_template(template: CsvTemplate, registry: Registry, template_root: Path) -> None:
    path = template_root / template.relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    headers = [registry.payload(column) for column in template.columns]
    values = [resolve(template.row.get(column, ""), registry) for column in template.columns]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(headers)
        writer.writerow(values)


def write_json_template(template: JsonTemplate, registry: Registry, template_root: Path) -> None:
    path = template_root / template.relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(resolve(template.payload, registry), indent=2) + "\n", encoding="utf-8")


def generate_templates(
    *, registry_csv: Path = DEFAULT_REGISTRY_CSV, template_root: Path = DEFAULT_TEMPLATE_ROOT
) -> list[Path]:
    """Generate all final data-kind preview templates and return written paths."""
    registry = Registry(registry_csv)
    written: list[Path] = []
    for template in CSV_TEMPLATES:
        write_csv_template(template, registry, template_root)
        written.append(template_root / template.relative_path)
    for template in JSON_TEMPLATES:
        write_json_template(template, registry, template_root)
        written.append(template_root / template.relative_path)
    return written


def check_templates(*, registry_csv: Path, template_root: Path) -> list[Path]:
    """Return committed template paths that differ from generated output."""
    with tempfile.TemporaryDirectory() as temp_dir:
        generated_root = Path(temp_dir)
        generate_templates(registry_csv=registry_csv, template_root=generated_root)
        changed: list[Path] = []
        for relative_path in all_template_paths():
            current = template_root / relative_path
            generated = generated_root / relative_path
            if not current.exists() or not filecmp.cmp(current, generated, shallow=False):
                changed.append(current)
        return changed


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry-csv", type=Path, default=DEFAULT_REGISTRY_CSV)
    parser.add_argument("--template-root", type=Path, default=DEFAULT_TEMPLATE_ROOT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed templates differ from generated output",
    )
    args = parser.parse_args(argv)

    if args.check:
        changed = check_templates(registry_csv=args.registry_csv, template_root=args.template_root)
        if changed:
            print("data-kind preview templates are stale:")
            for path in changed:
                print(path)
            return 1
        print("data-kind preview templates are current")
        return 0

    written = generate_templates(registry_csv=args.registry_csv, template_root=args.template_root)
    for path in written:
        print(path.relative_to(REPO_ROOT) if path.is_relative_to(REPO_ROOT) else path)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
